### ISSUE TITLE
Header Text No Longer Cyan in Reader Mode after Obsidian 0.15.6 Update

### ISSUE THREAD

**Issue by muya** [Slowbad/obsidian-solarized#23]
## Description
After upgrading to Obsidian 0.15.6, the headers in Reader mode are no longer cyan in colour; instead, they are gray, similar to the main text

## Steps To Reproduce
- Create a new vault in Obsidian 0.15.6
- Install the Solarized theme from the "Appearance" section under preferences
- Create a new note
- Add one or more Header markdown sections:
```
# H1 Header
Some text

## H2 Header
```
<img width="2182" alt="H1 Header Content in Editing Mode" src="https://user-images.githubusercontent.com/1861055/178929300-749f9b1c-5f80-4636-9721-d55d39992ffd.png">
- Switch to "Reader Mode"

### Expected
- In "Reader Mode", the headers should be in colour "cyan"

### Actual
- In "Reader Mode", the headers are also in colour "gray", similar to the text

<img width="2146" alt="H1 Header Content in Reader Mode" src="https://user-images.githubusercontent.com/1861055/178929285-6c6c5022-c9fd-4044-ae9a-a4e68588d460.png">

## Environment Details
```
OS Version: macOS 12.4
Obsidian Version: Version 0.15.6 (installer 0.14.15)
Solarized Theme Version: Latest
```

**Comment by carlosasterisk** [comment]
I have the same problem in the latest version 0.15.6. In reader mode, the header is in cyan. What can I do to fix it? Thank you!

**Comment by iancustoica** [comment]
Hello,

Before reading on please note I do not work with css so my fix might not be the best or most elegant solution.

I have the same issue with this theme after updating obsidian and even though I do not understand the root cause I made a fix for it by looking at another theme and pasting some code that controls headings (1-6) properties. I focused only on the light theme, so if you just want the same color (cyan) for every heading you need to manually change the variables from for ex: "color: var(--text-title-h5) !important;" to "color: var(--text-title) !important;"

I suggest you create a new css file in your obsidian vault/.obsidian/themes and experiment with it so if the solarized theme gets updated you won't have any problems or conflicts.

Here's a gist of my changes, hope it helps:

https://gist.github.com/iancustoica/7f6e7095a8bf6a74aec2497d9e40a587

**Comment by marchank0** [comment]
I made a pull request with a fix
for now you may add this code into css
```css
[data-heading] {
    color: var(--text-title) !important;
}
```

**Comment by muya** [comment]
> I made a pull request with a fix for now you may add this code into css
> 
> ```css
> [data-heading] {
>     color: var(--text-title) !important;
> }
> ```

Nice, @marchank0 - this is working 👍🏽

**Comment by carlosasterisk** [comment]
> I made a pull request with a fix for now you may add this code into css
> 
> ```css
> [data-heading] {
>     color: var(--text-title) !important;
> }
> ```

Does it work for Inline title?

**Comment by marchank0** [comment]
@carlosasterisk 
could you please provide example in md format to check what do you mean?

**Comment by harmtemolder** [comment]
Should be fixed with the new release. Could you test, please?

**Comment by muya** [comment]
> Should be fixed with the new release. Could you test, please?

@harmtemolder This seems to be working - thank you so much!
