### ISSUE TITLE
Code is not highlighted correctly in reading mode

### ISSUE THREAD

**Issue by marchank0** [Slowbad/obsidian-solarized#27]
Editing mode:
<img width="858" alt="obs-code-editing" src="https://user-images.githubusercontent.com/1183579/197543063-d9da9616-e8de-41d1-b927-7d0647f9df69.png">

Reading mode - BUG:
<img width="828" alt="obs-code-reading" src="https://user-images.githubusercontent.com/1183579/197543175-b4ade904-2402-4e7c-9e0e-2f69ff046848.png">

**Comment by harmtemolder** [comment]
Should be fixed with the new release. Could you test, please?

**Comment by marchank0** [comment]
@harmtemolder 
it's better, but as you can see there is a noticeable difference in highlighting 

![6A3D9784-CE62-49CD-9B0F-7E0FB474B2AD](https://user-images.githubusercontent.com/1183579/203323719-10244f55-4064-4692-8426-135372263d98.jpeg)
![B6501E66-375B-4DA7-BC3F-E5D1B64780B3](https://user-images.githubusercontent.com/1183579/203323738-9e9fa420-d9b5-4886-bdaf-b4f0f3ef2a9c.jpeg)

```python
class BinarySearch:
	def search(self, nums: List[int], target: int) -> int:
		l = 0
		r = len(objects) - 1
		while (l <= r):
			mid = (l + r) // 2
			guess = objects[mid]
			if (guess == target):
				return mid
			if (guess > target):
				r = mid
			else:
				l = mid + 1
		return None
```

**Comment by harmtemolder** [comment]
Thanks for pointing that out.

I went through all the code colors again, trying to match these as closely to the Python examples here: https://ethanschoonover.com/solarized/#python-vim

This is the result:

Editing view:

![image](https://user-images.githubusercontent.com/8167752/203490175-eb8a8c06-1ae0-4deb-b59c-abeae6b858b3.png)

Reading view:

![image](https://user-images.githubusercontent.com/8167752/203490220-cc386505-268f-481d-b196-8ec7d4a1dadf.png)

The fact that they are not 100% consistent (the `None`) is because Obsidian's own CSS is not 100% consistent. But I hope this is close enough for you.

**Comment by marchank0** [comment]
@harmtemolder 
this is splendid work!

**Comment by harmtemolder** [comment]
Haha, you're welcome
