### ISSUE TITLE
Should fonts be included, or not?

### ISSUE THREAD

**Issue by harmtemolder** [Slowbad/obsidian-solarized#29]
* In my Obsidian, I've got `Settings > Editor > Default editing mode` set to `Source mode`.
* I use a CSS snippet to use [Open Sans](https://wikiless.org/wiki/Open_Sans?lang=en) as interface and text font, and [JetBrains Mono](https://www.jetbrains.com/lp/mono/) as monospace font.
* The snippet then forces the editing view to use this monospace font for everything:

![image](https://user-images.githubusercontent.com/8167752/204757843-6d17664d-d11b-46bf-91e7-356f633afd9f.png)

What do you think: should fonts be included in this theme? (Remember that users can always use `Settings > Appearance > Font` to override them.)

**Comment by UweKrause** [comment]
Please not!
I just installed Obsidian and try out some settings, and I am right now confused that a theme (solarized) changes the fonts (that are possible to change just a few centimeters away!).

I especially don't like that the normal text font is forced monospaced. Please don't.

Otherwise, thanks a lot for making this solarized theme for Obsidian :)

**Comment by harmtemolder** [comment]
Wait, did that happen when you installed Solarized through Obsidian? Because I was under the impression that Obsidian uses the `main` GitHub branch, which does not include any fonts. (The `dev` branch does, so just in case, I'll delete that.)

**Comment by harmtemolder** [comment]
#32 is fixed, and I'll close this discussion
