### ISSUE TITLE
Scroll bars seem to have the wrong color

### ISSUE THREAD

**Issue by learnitmyway** [Slowbad/obsidian-solarized#31]
<img width="25" alt="Screenshot 2023-01-11 at 19 48 40" src="https://user-images.githubusercontent.com/12038670/211892448-e2d94d9e-28be-4230-b095-258db87c86b2.png">

**Comment by harmtemolder** [comment]
What version of Obsidian are you using (Settings > About)? And on what operating system?

**Comment by learnitmyway** [comment]
It doesn't look like that anymore, but the last Obsidian release seems to have been 3 weeks ago and I downloaded Obsidian this week 🤔. Anyway, guess I'll close it. Thanks for quick response! Btw why would the OS matter? Obsidian version I understand

**Comment by learnitmyway** [comment]
It's back 😕 . Obsidian: Version 1.1.9 (Installer 1.1.9), latest version of Mac OS

**Comment by harmtemolder** [comment]
I asked about the OS because I'm not sure how Obsidian (or the underlying Electron) handle scrollbars across different systems.

Do you have the same issue when using the "Default" theme?

**Comment by learnitmyway** [comment]
> I asked about the OS because I'm not sure how Obsidian (or the underlying Electron) handle scrollbars across different systems.

I see

This is how it looks with the default theme (in dark mode):

<img width="54" alt="Screenshot 2023-01-13 at 09 18 47" src="https://user-images.githubusercontent.com/12038670/212272043-94c16727-223d-45b6-ad61-6073bc65a34a.png">

I should add the the screenshot in the description is also dark mode in case that wasn't clear

**Comment by harmtemolder** [comment]
Judging from your two screenshots it looks like your machine ignores Obsidian's scroll bar styling completely: both are the same, and neither are what they should be:

Default:

![image](https://user-images.githubusercontent.com/8167752/212545401-71f76b63-982c-48c4-9a69-c151866537c5.png)

Solarized:

![image](https://user-images.githubusercontent.com/8167752/212545428-44446afd-fadf-402a-bbcc-4599b0b1829a.png)

I don't see an existing bug report for this yet: https://forum.obsidian.md/search?q=scroll+bars+mac

I suggest you to do that, because this is a deeper problem and cannot be fixed from the theme. Sorry I could not be of more help

**Comment by learnitmyway** [comment]
Didn't expect that. Thanks for looking into it!
