### ISSUE TITLE
Do not override a user's font as set under Appearance

### ISSUE THREAD

**Issue by dgailer** [Slowbad/obsidian-solarized#33]
I just did a fresh install of the Solarized Theme and the font in edit mode used the mono spaced font instead of the font I selected.

I found a work around by changing line 219 in theme.css. I added the font I wanted to use (which I had also selected in the Obsidian Appearance Menu) before monospace.

```
font-family: var(--font-'MS Reference Sans Serif', monospace); }
```

From reading some of the other issues this doesn't seem to be the intended behavior. Other themes work as intended with the selected font showing in edit mode.

Let me know if you need any more details.

Thanks!

**Comment by harmtemolder** [comment]
Thanks for submitting this issue.

I prefer to use a monospace in editing mode, so that's how that ended up in this theme. Since then, Obsidian have added the option for users to override fonts, so I've removed that part from the theme.

[v1.0.9-beta](https://github.com/harmtemolder/obsidian-solarized/releases/tag/v1.0.9-beta) should now respect the font you set in the appearance menu. Could you test this by uninstalling and reinstalling the theme?

**Comment by dgailer** [comment]
I have uninstalled and reinstalled the theme and it looks to be working correctly.

Thanks for looking into the issue.
